// Legal pages (Privacy Policy, Terms & Conditions, Refund Policy). These defaults are the
// pages' built-in content; admins can change them from Website Content > CMS (rich-text editor).
// Section bodies are HTML and are always cleaned (DOMPurify) before they are shown.
import DOMPurify from 'dompurify';

export const LEGAL_PAGE_KEYS = ['privacy', 'terms', 'refund'];

export const DEFAULT_LEGAL_CONTENT = {
  privacy: {
    title: "Privacy Policy",
    subtitle: "How ORDR collects, uses and protects your information.",
    lastUpdated: '29 September 2026',
    contactTitle: "Have a privacy question?",
    contactEmail: 'hello@ordr.in',
    sections: [
      { title: "Overview", html: "<p>ORDR (“ORDR”, “we”, “us”) is a B2B order-tracking platform. Businesses use ORDR to manage sales orders, purchase orders, shipments and deliveries in one place. This Privacy Policy explains what information we collect, how we use it, who we share it with and the choices you have. It applies to the ORDR website and web application. By creating an account or using ORDR, you agree to the practices described here.</p>" },
      { title: "Information We Collect", html: "<h4>Information you give us</h4><ul><li><strong>Account details:</strong> your name, work email, password (stored only as a secure hash), phone number, designation and GST number if you add them.</li><li><strong>Company details:</strong> company name, industry, country, timezone and your tracking preferences.</li><li><strong>Team details:</strong> email addresses and roles of colleagues you invite.</li><li><strong>Order data:</strong> orders, line items, customers and suppliers, shipments, tracking numbers (LR / AWB / GR), delivery dates and notes you enter.</li><li><strong>Documents:</strong> purchase orders and other files you upload (PDF, Excel, CSV, JPG, PNG).</li></ul><h4>Information from connected services</h4><ul><li><strong>Google sign-in:</strong> your name, email address and profile picture from your Google account.</li><li><strong>Gmail (only if you connect it):</strong> see the section <a href=\"#gmail-data\">Gmail Data</a> below.</li><li><strong>Payments:</strong> Razorpay processes card, UPI and bank details. We receive only the payment status, payment ID, plan and amount, never your full card or bank details.</li></ul><h4>Information collected automatically</h4><ul><li><strong>Usage events:</strong> actions such as signing up, connecting Gmail, creating an order or using search, so we can understand how ORDR is used. We do not record the text you type into search.</li><li><strong>Security logs:</strong> an audit log of important actions (for example orders created or edited, team changes) with the time and IP address.</li><li><strong>Session data:</strong> a login token stored in a cookie and in your browser’s local storage to keep you signed in.</li></ul>" },
      { title: "Gmail Data", html: "<p>Connecting Gmail is optional. When an admin connects a Gmail inbox:</p><ul><li>We request <strong>read-only</strong> access. ORDR never sends, deletes or changes your emails.</li><li>We read new emails to find likely orders and order updates (for example purchase orders, dispatch and delivery emails). Emails that look like marketing or newsletters are filtered out before any further processing.</li><li>For likely order emails we store the sender, subject, message text, received time and attachment names, and we download order attachments (PDF, Excel, CSV, images) to extract order details.</li><li>Access and refresh tokens are <strong>encrypted</strong> before they are stored.</li><li>You can disconnect Gmail at any time from Integrations. Disconnecting deletes the stored tokens immediately. You can also remove ORDR’s access from your Google Account settings.</li></ul><p>ORDR’s use and transfer of information received from Google APIs adheres to the <a href=\"https://developers.google.com/terms/api-services-user-data-policy\" target=\"_blank\" rel=\"noopener noreferrer\">Google API Services User Data Policy</a>, including the Limited Use requirements. Gmail data is used only to provide ORDR’s order detection features to you, is not used for advertising, is not sold, and is not used to train general AI models.</p>" },
      { title: "AI Processing", html: "<p>ORDR uses artificial intelligence (Google Gemini) to classify emails and to extract order details such as PO number, customer or supplier, items, quantities and dates from emails and documents.</p><ul><li>Only the content needed for that task is sent to the AI service.</li><li>The AI is instructed never to guess: missing information is left empty.</li><li><strong>AI never creates or changes an official order by itself.</strong> Every detection and every suggested update waits in the AI Order Inbox until a person in your team reviews and confirms it.</li></ul>" },
      { title: "How We Use Information", html: "<ul><li>To provide ORDR: accounts, orders, shipments, tracking, alerts, reports and notifications.</li><li>To detect orders and order updates from connected email and uploaded documents.</li><li>To send service emails: sign-in codes, team invitations, alerts you have enabled, and payment confirmations with invoices.</li><li>To process subscriptions and payments and to enforce plan limits.</li><li>To keep ORDR secure, prevent misuse and investigate problems.</li><li>To understand usage and improve the product.</li><li>To meet legal, tax and accounting obligations.</li></ul>" },
      { title: "How We Share Information", html: "<p>We do <strong>not</strong> sell your data. We share information only with:</p><ul><li><strong>Your team:</strong> people in your company account see the company’s orders, shipments and documents according to their role.</li><li><strong>Service providers</strong> that run ORDR for us: cloud hosting and database providers, Google (sign-in, Gmail and Gemini AI), Razorpay (payments) and our email delivery provider. They may use the data only to provide their service to us.</li><li><strong>Legal reasons:</strong> when required by law, or to protect the rights, property or safety of ORDR, our users or others.</li><li><strong>Business transfers:</strong> if ORDR is merged or acquired, your information may move to the new owner under this policy.</li></ul><p>Each company’s data is kept separate. One company can never see another company’s orders, documents or emails.</p>" },
      { title: "Cookies & Local Storage", html: "<p>ORDR uses a small number of essential browser storage items:</p><ul><li>A secure, HTTP-only login cookie and a login token in local storage, to keep you signed in.</li><li>Simple preferences, such as your choice for the auto-renew switch on the Billing page.</li></ul><p>We do not use advertising or third-party tracking cookies. Blocking these items will stop you from signing in.</p>" },
      { title: "Data Security", html: "<ul><li>All traffic is encrypted with HTTPS.</li><li>Passwords are stored as one-way hashes; Gmail tokens are encrypted.</li><li>Strict company-level separation of data and role-based access (Admin / Member).</li><li>Uploaded files are checked for type and size before they are accepted.</li><li>Changing or resetting your password signs out your other sessions.</li><li>Important actions are recorded in an audit log.</li></ul>" },
      { title: "Data Retention", html: "<p>We keep your data for as long as your company account is active.</p><ul><li>When a trial or plan ends, your data is <strong>not</strong> deleted: the account becomes read-only until you choose a plan.</li><li>Your plan decides how much order history is shown; older completed orders are hidden, not deleted.</li><li>Payment records and invoices are kept as long as tax and accounting laws require.</li><li>If you ask us to delete your account, we delete or anonymise your data within a reasonable time, except records we must keep by law.</li></ul>" },
      { title: "Your Rights & Choices", html: "<ul><li><strong>Access and correction:</strong> view and update your profile and company details in Settings.</li><li><strong>Email notifications:</strong> turn optional notification emails on or off in Settings → Notifications.</li><li><strong>Gmail:</strong> disconnect at any time from Integrations.</li><li><strong>Deletion and export:</strong> ask us to export or delete your data by writing to <a href=\"mailto:hello@ordr.in\">hello@ordr.in</a>.</li><li><strong>Withdraw consent:</strong> where we rely on your consent, you can withdraw it at any time.</li></ul>" },
      { title: "Children's Privacy", html: "<p>ORDR is a business service and is not meant for children. We do not knowingly collect information from anyone under 18.</p>" },
      { title: "Changes to This Policy", html: "<p>We may update this policy from time to time. The “Last updated” date at the top shows when it last changed. For important changes we will notify account admins by email or in the app.</p>" },
      { title: "Contact Us", html: "<p>Questions about this policy or your data? Write to us at <a href=\"mailto:hello@ordr.in\">hello@ordr.in</a>.</p>" },
    ],
  },
  terms: {
    title: "Terms & Conditions",
    subtitle: "The rules for using ORDR, in plain language.",
    lastUpdated: '29 September 2026',
    contactTitle: "Have a question about these terms?",
    contactEmail: 'hello@ordr.in',
    sections: [
      { title: "Acceptance of These Terms", html: "<p>These Terms &amp; Conditions (“Terms”) govern your use of ORDR, the B2B order-tracking platform provided by ORDR Technologies (“ORDR”, “we”, “us”), including the website and web application.</p><p>By creating an account, starting a trial or using ORDR, you agree to these Terms and to our <a href=\"/privacy-policy\">Privacy Policy</a>. If you use ORDR for a company, you confirm that you are authorised to accept these Terms on its behalf; “you” then also means that company.</p>" },
      { title: "The Service", html: "<p>ORDR helps businesses track sales orders, purchase orders, shipments and deliveries in one place. Orders can come into ORDR by:</p><ul><li>connecting a Gmail inbox, where AI detects likely orders and order updates,</li><li>uploading purchase orders and documents (PDF, Excel, CSV, JPG, PNG), or</li><li>adding orders manually.</li></ul><p>We may improve, change or add features over time. Features marked “Coming soon” are not part of the service until they are released.</p>" },
      { title: "Accounts & Security", html: "<ul><li>You must give accurate information when you sign up and keep it up to date.</li><li>You are responsible for keeping your password safe and for all activity under your account.</li><li>Tell us straight away at <a href=\"mailto:hello@ordr.in\">hello@ordr.in</a> if you suspect unauthorised use of your account.</li><li>You must be at least 18 years old and use ORDR for business purposes.</li></ul>" },
      { title: "Company Workspace, Team & Roles", html: "<p>Each company has its own workspace. Its data is kept separate from every other company.</p><ul><li><strong>Admins</strong> manage users, roles, company settings, Gmail connections, notifications and billing.</li><li><strong>Members</strong> can view and create orders, update order status and add shipment information.</li><li>Admins are responsible for who they invite and for the role they give each person. A workspace always keeps at least one active admin.</li><li>The number of users depends on your plan.</li></ul>" },
      { title: "Free Trial, Plans & Limits", html: "<ul><li>New companies get a <strong>14-day free trial</strong> with the core features. No credit card is needed to start.</li><li>After the trial, continued use needs a paid plan: <strong>Basic, Growth, Business or Pro</strong>, as listed on our pricing page.</li><li>Each plan has limits, for example users, orders per month, Gmail inboxes, AI extractions and order history. When a limit is reached, the related action is paused until the next period or an upgrade.</li><li>Some features are only in some plans (for example Excel export, priority support and advanced reporting).</li></ul><p><strong>When a trial or plan ends, your data is not deleted.</strong> The workspace becomes read-only until you choose a plan.</p>" },
      { title: "Payments, Renewal & Cancellation", html: "<ul><li>Prices are shown in Indian Rupees (INR) per month and include GST where applicable. Payments are processed by Razorpay.</li><li><strong>One-time payment:</strong> pays for one month of the chosen plan.</li><li><strong>Auto-renew:</strong> if you turn it on, your plan renews and is charged automatically every month until you cancel.</li><li>You can cancel auto-renew at any time from Billing. Your plan stays active until the end of the period already paid for, and you are not charged again.</li><li>If you switch plans during a paid period, the unused value of your current plan is credited as extra days on the new plan.</li><li>An invoice or receipt is available in Billing and is emailed after each payment.</li><li>Payments are non-refundable, except where required by law or described in our <a href=\"/refund-policy\">Refund Policy</a>.</li><li>We may change prices with prior notice. New prices apply from your next billing period.</li></ul>" },
      { title: "Your Data", html: "<p><strong>You own your data</strong>: orders, shipments, documents, emails and other content you or your team add to ORDR (“Customer Data”).</p><ul><li>You give us permission to store and process Customer Data only to provide and improve ORDR for you, as described in the <a href=\"/privacy-policy\">Privacy Policy</a>.</li><li>You confirm that you have the right to upload or connect this data, including any personal data of your customers, suppliers or colleagues.</li><li>We do not sell Customer Data.</li></ul>" },
      { title: "AI Features", html: "<p>ORDR uses AI to classify emails and to read order details from emails and documents. AI can make mistakes: it may miss information or read it wrongly.</p><ul><li>AI results are <strong>suggestions</strong>. ORDR never creates or changes an official order until a person in your team reviews and confirms it.</li><li>You are responsible for checking detected details (for example PO numbers, quantities, prices and dates) before you confirm them.</li><li>Confidence scores help you decide what to check; they are not a guarantee.</li></ul>" },
      { title: "Gmail & Third-Party Services", html: "<ul><li>Connecting Gmail is optional. ORDR asks for read-only access and never sends, deletes or changes your emails.</li><li>Your use of Google, Razorpay and other connected services is also subject to their own terms.</li><li>We are not responsible for outages or changes in third-party services, but we will do our best to limit any effect on ORDR.</li></ul>" },
      { title: "Acceptable Use", html: "<p>You agree not to:</p><ul><li>use ORDR for anything unlawful, fraudulent or harmful;</li><li>upload viruses or malicious files, or content you have no right to share;</li><li>try to access another company’s workspace or data, or get around security or plan limits;</li><li>overload, scrape, copy or reverse-engineer the service;</li><li>resell or share access to ORDR outside your company without our written permission.</li></ul>" },
      { title: "Intellectual Property", html: "<p>ORDR, including its software, design, logos and content (other than Customer Data), belongs to ORDR Technologies and is protected by law. We give you a limited, non-exclusive, non-transferable right to use ORDR for your business during your subscription. Feedback you send us may be used to improve ORDR without any obligation to you.</p>" },
      { title: "Availability & Support", html: "<p>We work to keep ORDR available and secure, but we do not promise that it will always be uninterrupted or error free. Planned maintenance or events outside our control may cause short breaks. Support is available by email; priority support is included in the Business and Pro plans.</p>" },
      { title: "Suspension & Termination", html: "<ul><li>You may stop using ORDR at any time and ask us to close your account.</li><li>We may suspend or close an account that breaks these Terms, is not paid, or puts ORDR or other users at risk. Where reasonable, we will warn you first.</li><li>After closure, you can ask for an export of your data within a reasonable time. Data is then deleted as described in the Privacy Policy, except records we must keep by law.</li></ul>" },
      { title: "Disclaimer & Limitation of Liability", html: "<p>ORDR is provided “as is” and “as available”. To the extent allowed by law, we are not liable for indirect or consequential losses, such as lost profits, lost business or lost data, or for decisions made on the basis of information in ORDR that was not checked.</p><p>Our total liability for any claim relating to ORDR is limited to the amount you paid us for the service in the three months before the claim.</p>" },
      { title: "Governing Law", html: "<p>These Terms are governed by the laws of India. Any dispute will be subject to the exclusive jurisdiction of the courts in Mumbai, Maharashtra.</p>" },
      { title: "Changes to These Terms", html: "<p>We may update these Terms from time to time. The “Last updated” date at the top shows when they last changed. For important changes we will notify account admins by email or in the app. Continuing to use ORDR after a change means you accept the updated Terms.</p>" },
      { title: "Contact Us", html: "<p>Questions about these Terms? Write to us at <a href=\"mailto:hello@ordr.in\">hello@ordr.in</a>.</p>" },
    ],
  },
  refund: {
    title: "Refund Policy",
    subtitle: "How payments, cancellations and refunds work for ORDR plans.",
    lastUpdated: '29 September 2026',
    contactTitle: "Need help with a payment?",
    contactEmail: 'hello@ordr.in',
    sections: [
      { title: "Overview", html: "<p>This Refund Policy explains how payments, cancellations and refunds work for ORDR subscriptions. It is part of our <a href=\"/terms-and-conditions\">Terms &amp; Conditions</a>.</p><p>We want you to be sure ORDR is right for your business before you pay. That is why every new company starts with a free trial.</p>" },
      { title: "Free Trial", html: "<ul><li>Every new company gets a <strong>14-day free trial</strong> with the core features.</li><li>No credit card is needed to start, so nothing is charged during the trial.</li><li>When the trial ends, nothing is charged automatically. Your workspace becomes read-only until you choose a plan, and your data is kept.</li></ul>" },
      { title: "Plan Payments", html: "<p>Plans (Basic, Growth, Business and Pro) are billed monthly in Indian Rupees, including GST where applicable. You can pay in two ways:</p><ul><li><strong>One-time payment:</strong> pays for one month of the chosen plan. It does not renew on its own.</li><li><strong>Auto-renew:</strong> your plan is charged automatically every month until you cancel.</li></ul><p>Because you can try ORDR free for 14 days first, <strong>payments for a plan period are non-refundable</strong>, including for unused days, unused limits or partial months, except in the cases listed below or where the law requires a refund.</p>" },
      { title: "Cancelling Auto-Renew", html: "<ul><li>You can turn off auto-renew at any time from <strong>Billing</strong> in the app (admins only).</li><li>After cancelling, you are <strong>not charged again</strong>. Your plan stays active until the end of the period you have already paid for.</li><li>To avoid the next charge, cancel before your renewal date. A renewal that has already been charged is not refunded.</li></ul>" },
      { title: "Upgrades & Plan Changes", html: "<ul><li>If you move to another plan while your current plan is still active, the <strong>unused value of your current plan is credited as extra days</strong> on the new plan. You do not lose what you have paid for.</li><li>This credit is given as plan time, not as money back.</li></ul>" },
      { title: "When We Do Refund", html: "<p>We will refund the amount in these cases:</p><ul><li><strong>Duplicate payment:</strong> you were charged more than once for the same plan period.</li><li><strong>Payment error:</strong> money was taken but the payment failed or the plan was not activated, and we cannot activate it for you.</li><li><strong>Charge after cancellation:</strong> you were charged for a renewal even though auto-renew was cancelled before the renewal date.</li><li><strong>Service unavailable:</strong> ORDR was unusable for most of your paid period because of a problem on our side. In this case we may refund part of the period or add free days.</li><li>Any other case where a refund is required by law.</li></ul>" },
      { title: "How to Request a Refund", html: "<p>Email us at <a href=\"mailto:hello@ordr.in\">hello@ordr.in</a> within <strong>7 days</strong> of the payment with:</p><ul><li>your company name and the email address of your ORDR account,</li><li>the invoice or receipt number (shown in Billing and in your payment email) or the Razorpay payment ID, and</li><li>a short description of the problem.</li></ul><p>We reply within 2 business days and tell you whether the refund is approved.</p>" },
      { title: "How Refunds Are Paid", html: "<ul><li>Approved refunds are made to the <strong>original payment method</strong> through Razorpay.</li><li>Refunds usually reach your account within <strong>5 to 7 business days</strong> after approval; your bank may take longer.</li><li>For a refunded period, the plan may be ended or reduced to match the refund.</li></ul>" },
      { title: "Account Closure", html: "<p>If you close your account or stop using ORDR, payments already made are not refunded, except in the cases above. You can ask us to export your data before the account is closed, as described in our <a href=\"/privacy-policy\">Privacy Policy</a>.</p>" },
      { title: "Changes to This Policy", html: "<p>We may update this policy from time to time. The “Last updated” date at the top shows when it last changed. Changes do not affect payments made before the change.</p>" },
      { title: "Contact Us", html: "<p>Questions about a payment or refund? Write to us at <a href=\"mailto:hello@ordr.in\">hello@ordr.in</a>.</p>" },
    ],
  },
};

// Only simple formatting is allowed on the page: paragraphs, bold/italic/underline,
// sub-headings, lists and links (no scripts, styles or images)
const ALLOWED = {
  ALLOWED_TAGS: ['p', 'br', 'strong', 'b', 'em', 'i', 'u', 's', 'h3', 'h4', 'ul', 'ol', 'li', 'a'],
  ALLOWED_ATTR: ['href', 'target', 'rel'],
  ALLOWED_URI_REGEXP: /^(?:https?:|mailto:|tel:|\/|#)/i,
};
export const cleanLegalHtml = (html) => DOMPurify.sanitize(String(html || ''), ALLOWED);

// Saved page on top of the default; a missing or broken section list falls back to the default
export const mergeLegalContent = (page, saved) => {
  const defaults = DEFAULT_LEGAL_CONTENT[page];
  const custom = saved && typeof saved === 'object' ? saved : {};
  const merged = { ...defaults, ...custom };
  if (!Array.isArray(merged.sections)) merged.sections = defaults.sections;
  merged.sections = merged.sections
    .filter((s) => s && typeof s === 'object')
    .map((s) => ({ title: String(s.title || ''), html: String(s.html || '') }));
  return merged;
};

// "#section" ids for each section title (for links inside the page)
export const sectionId = (title, index) =>
  String(title || '').toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || `section-${index + 1}`;
