export function exportToCSV(data, filename) {
  if (!data || data.length === 0) return;

  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(','),
    ...data.map(row =>
      headers.map(h => {
        let val = row[h];
        if (typeof val === 'string' && (val.includes(',') || val.includes('"'))) {
          val = `"${val.replace(/"/g, '""')}"`;
        }
        return val;
      }).join(',')
    ),
  ];

  const csvString = csvRows.join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}_${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function printPage(title, tableSelector) {
  const printWindow = window.open('', '_blank');
  let content = '';

  if (tableSelector) {
    const table = document.querySelector(tableSelector);
    if (table) content = table.outerHTML;
  } else {
    const el = document.querySelector('.page-content');
    if (el) content = el.innerHTML;
  }

  if (!content) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title} - ORDR</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', Arial, sans-serif; padding: 24px; color: #1a1a2e; }
        .print-header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #2D4735; padding-bottom: 16px; }
        .print-header h1 { font-size: 22px; font-weight: 700; color: #2D4735; letter-spacing: -0.5px; }
        .print-header p { font-size: 12px; color: #626884; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #2D4735; color: #fff; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; padding: 10px 12px; text-align: left; }
        td { padding: 10px 12px; font-size: 13px; border-bottom: 1px solid #e8e8e8; color: #1a1a2e; }
        tbody tr:nth-child(even) { background: #f8f9fa; }
        tbody tr:hover { background: #f0f0f5; }
        .status-badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 11px; font-weight: 500; }
        .processing { background: #fff3e0; color: #e65100; }
        .in-transit { background: #e1f5fe; color: #0277bd; }
        .ready-dispatch { background: #e8f5e9; color: #2e7d32; }
        .dispatched { background: #e3f2fd; color: #1565c0; }
        .delayed { background: #ffebee; color: #c62828; }
        .delivered { background: #e8f5e9; color: #1b5e20; }
        .print-footer { text-align: center; margin-top: 20px; padding-top: 12px; border-top: 1px solid #e0e0e0; font-size: 11px; color: #999; }
        @media print {
          body { padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          th { background: #2D4735 !important; color: #fff !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
      </style>
    </head>
    <body>
      <div class="print-header">
        <h1>ORDR</h1>
        <p>${title}</p>
        <p>Printed on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
      </div>
      ${content}
      <div class="print-footer">Generated by ORDR - B2B Order Management Platform</div>
    </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 500);
}
