export const timezones = [
  { value: "Pacific/Midway", label: "(GMT-11:00) Midway Island, Samoa" },
  { value: "America/Adak", label: "(GMT-10:00) Hawaii-Aleutian" },
  { value: "Pacific/Honolulu", label: "(GMT-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(GMT-09:00) Alaska" },
  { value: "America/Los_Angeles", label: "(GMT-08:00) Pacific Time (US & Canada)" },
  { value: "America/Denver", label: "(GMT-07:00) Mountain Time (US & Canada)" },
  { value: "America/Phoenix", label: "(GMT-07:00) Arizona" },
  { value: "America/Chicago", label: "(GMT-06:00) Central Time (US & Canada)" },
  { value: "America/Mexico_City", label: "(GMT-06:00) Mexico City" },
  { value: "America/New_York", label: "(GMT-05:00) Eastern Time (US & Canada)" },
  { value: "America/Bogota", label: "(GMT-05:00) Bogota, Lima, Quito" },
  { value: "America/Halifax", label: "(GMT-04:00) Atlantic Time (Canada)" },
  { value: "America/Caracas", label: "(GMT-04:00) Caracas, La Paz" },
  { value: "America/Argentina/Buenos_Aires", label: "(GMT-03:00) Buenos Aires" },
  { value: "America/Sao_Paulo", label: "(GMT-03:00) Brasilia" },
  { value: "Atlantic/South_Georgia", label: "(GMT-02:00) Mid-Atlantic" },
  { value: "Atlantic/Cape_Verde", label: "(GMT-01:00) Cape Verde Is." },
  { value: "Europe/London", label: "(GMT+00:00) London, Edinburgh, Dublin, Lisbon" },
  { value: "Africa/Casablanca", label: "(GMT+00:00) Casablanca, Monrovia" },
  { value: "Europe/Berlin", label: "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
  { value: "Europe/Paris", label: "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris" },
  { value: "Africa/Lagos", label: "(GMT+01:00) West Central Africa" },
  { value: "Europe/Athens", label: "(GMT+02:00) Athens, Bucharest, Istanbul" },
  { value: "Africa/Cairo", label: "(GMT+02:00) Cairo" },
  { value: "Africa/Johannesburg", label: "(GMT+02:00) Harare, Pretoria" },
  { value: "Europe/Moscow", label: "(GMT+03:00) Moscow, St. Petersburg, Volgograd" },
  { value: "Asia/Riyadh", label: "(GMT+03:00) Kuwait, Riyadh" },
  { value: "Asia/Dubai", label: "(GMT+04:00) Abu Dhabi, Muscat" },
  { value: "Asia/Baku", label: "(GMT+04:00) Baku, Tbilisi, Yerevan" },
  { value: "Asia/Kabul", label: "(GMT+04:30) Kabul" },
  { value: "Asia/Karachi", label: "(GMT+05:00) Islamabad, Karachi, Tashkent" },
  { value: "Asia/Yekaterinburg", label: "(GMT+05:00) Ekaterinburg" },
  { value: "Asia/Kolkata", label: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
  { value: "Asia/Kathmandu", label: "(GMT+05:45) Kathmandu" },
  { value: "Asia/Dhaka", label: "(GMT+06:00) Astana, Dhaka" },
  { value: "Asia/Almaty", label: "(GMT+06:00) Almaty, Novosibirsk" },
  { value: "Asia/Rangoon", label: "(GMT+06:30) Yangon (Rangoon)" },
  { value: "Asia/Bangkok", label: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
  { value: "Asia/Krasnoyarsk", label: "(GMT+07:00) Krasnoyarsk" },
  { value: "Asia/Shanghai", label: "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi" },
  { value: "Asia/Singapore", label: "(GMT+08:00) Kuala Lumpur, Singapore" },
  { value: "Asia/Taipei", label: "(GMT+08:00) Taipei" },
  { value: "Asia/Irkutsk", label: "(GMT+08:00) Irkutsk, Ulaan Bataar" },
  { value: "Asia/Tokyo", label: "(GMT+09:00) Osaka, Sapporo, Tokyo" },
  { value: "Asia/Seoul", label: "(GMT+09:00) Seoul" },
  { value: "Asia/Yakutsk", label: "(GMT+09:00) Yakutsk" },
  { value: "Australia/Adelaide", label: "(GMT+09:30) Adelaide" },
  { value: "Australia/Darwin", label: "(GMT+09:30) Darwin" },
  { value: "Australia/Brisbane", label: "(GMT+10:00) Brisbane" },
  { value: "Australia/Sydney", label: "(GMT+10:00) Canberra, Melbourne, Sydney" },
  { value: "Asia/Vladivostok", label: "(GMT+10:00) Vladivostok" },
  { value: "Asia/Magadan", label: "(GMT+11:00) Magadan, Solomon Is., New Caledonia" },
  { value: "Pacific/Auckland", label: "(GMT+12:00) Auckland, Wellington" },
  { value: "Pacific/Fiji", label: "(GMT+12:00) Fiji, Kamchatka, Marshall Is." },
  { value: "Pacific/Tongatapu", label: "(GMT+13:00) Nuku'alofa" }
];
